#ifndef TODAIGRAPH_CONSTANTS_H
#define TODAIGRAPH_CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define MAX_NODES 100

#define NODE_RADIUS 10
#define SELECTION_RADIUS NODE_RADIUS

#define EDGE_WIDTH 3
#define SELECTION_DIST 5

#define HISTSIZE 10

#endif // TODAIGRAPH_CONSTANTS_H
