#ifndef TODAIGRAPH_CONSTANTS_H
#define TODAIGRAPH_CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define MAX_NODES 100

#define NODE_RADIUS 10
#define SELECTION_DISTANCE NODE_RADIUS

#endif // TODAIGRAPH_CONSTANTS_H
